image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    init: uv sync --frozen --no-install-project --no-dev
    command: streamlit run app.py

ports:
  - port: 8501
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.vscode-jupyter-slideshow
    - streamlit.streamlit