version: '3'

services:
  financials:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
