tasks:
    command-0:
        command: streamlit run src/financials/app.py
        dependsOn:
            - init-000
        description: init task migrated from .gitpod.yml
        name: 'Install dependencies: command'
        triggeredBy:
            - postDevcontainerStart
    init-000:
        command: uv sync --frozen --no-install-project --no-dev
        description: init task migrated from .gitpod.yml
        name: 'Install dependencies: init'
